# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 04:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('preparacion', 'Preparación'), ('negociacion', 'Negociación'), ('ejecucion', 'Ejecución'), ('evaluacion', 'Evaluación')], default='preparacion', max_length=11, verbose_name='Fase de la acción')),
                ('name', models.CharField(max_length=64, verbose_name='Nombre')),
                ('toDo', models.TextField(max_length=512, verbose_name='¿Qué y como se realizará?')),
                ('satisfactions', models.TextField(max_length=512, verbose_name='Condiciones de satisfacción')),
                ('expire_at', models.DateField(verbose_name='Fecha límite de la fase')),
                ('begin_at', models.DateField(verbose_name='Fecha de inicio')),
                ('accomplish_at', models.DateField(verbose_name='Fecha de cumplimiento')),
                ('renegotiation_at', models.DateField(verbose_name='Fecha de regenociación')),
                ('report_at', models.DateField(verbose_name='Fecha de reporte de Avance')),
                ('financial', models.CharField(max_length=64, verbose_name='Financieros')),
                ('operational', models.CharField(max_length=64, verbose_name='Operacionales')),
                ('other1', models.CharField(max_length=64, verbose_name='Otros')),
                ('other2', models.CharField(max_length=64, verbose_name='Otros')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_action', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_create_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('observer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_action', to=settings.AUTH_USER_MODEL, verbose_name='Observador')),
                ('parent_action', models.ManyToManyField(blank=True, related_name='_action_parent_action_+', to='workflow.Action', verbose_name='Acción hija')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_action', to=settings.AUTH_USER_MODEL, verbose_name='Realizador')),
            ],
            options={
                'verbose_name': 'Acción',
                'verbose_name_plural': 'Acciones',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nombre')),
                ('clasification', models.CharField(choices=[('estandar', 'Estándar'), ('piloto', 'Piloto'), ('jardin', 'Jardín')], default='estandar', max_length=8, verbose_name='Tipos de proyecto')),
                ('phase', models.CharField(choices=[('preparacion', 'Preparación'), ('negociacion', 'Negociación'), ('ejecucion', 'Ejecución'), ('evaluacion', 'Evaluación')], default='preparacion', max_length=11, verbose_name='Fase de proyecto')),
                ('toDo', models.TextField(max_length=512, verbose_name='¿Qué y como se realizará?')),
                ('satisfactions', models.TextField(max_length=512, verbose_name='Condiciones de satisfacción')),
                ('preparation_at', models.DateField(verbose_name='Fecha de preparación')),
                ('negotiation_at', models.DateField(verbose_name='Fecha de negociación')),
                ('execution_at', models.DateField(verbose_name='Fecha de ejecución')),
                ('evaluation_at', models.DateField(verbose_name='Fecha de evaluación')),
                ('begin_at', models.DateField(verbose_name='Fecha de inicio')),
                ('accomplish_at', models.DateField(verbose_name='Fecha de cumplimiento')),
                ('renegotiation_at', models.DateField(verbose_name='Fecha de regenociación')),
                ('report_at', models.DateField(verbose_name='Fecha de reporte de Avance')),
                ('financial', models.CharField(max_length=64, verbose_name='Financieros')),
                ('operational', models.CharField(max_length=64, verbose_name='Operacionales')),
                ('other1', models.CharField(max_length=64, verbose_name='Otros')),
                ('other2', models.CharField(max_length=64, verbose_name='Otros')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_project', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_create_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('observer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_project', to=settings.AUTH_USER_MODEL, verbose_name='Observador')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_project', to=settings.AUTH_USER_MODEL, verbose_name='Realizador')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.AddField(
            model_name='action',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='workflow.Project', verbose_name='Proyecto relacionado'),
        ),
    ]
