# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='financial',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Financieros'),
        ),
        migrations.AlterField(
            model_name='action',
            name='operational',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Operacionales'),
        ),
        migrations.AlterField(
            model_name='action',
            name='other1',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Otros'),
        ),
        migrations.AlterField(
            model_name='action',
            name='other2',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Otros'),
        ),
        migrations.AlterField(
            model_name='project',
            name='financial',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Financieros'),
        ),
        migrations.AlterField(
            model_name='project',
            name='operational',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Operacionales'),
        ),
        migrations.AlterField(
            model_name='project',
            name='other1',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Otros'),
        ),
        migrations.AlterField(
            model_name='project',
            name='other2',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Otros'),
        ),
    ]
