# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170309_1525'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('preparacion', 'Preparación'), ('negociacion', 'Negociación'), ('ejecucion', 'Ejecución'), ('evaluacion', 'Evaluación')], default='preparacion', max_length=11, verbose_name='Fase de la acción')),
                ('name', models.CharField(max_length=64, verbose_name='Nombre')),
                ('toDo', models.TextField(max_length=512, verbose_name='¿Qué y como se realizará?')),
                ('satisfactions', models.TextField(max_length=512, verbose_name='Condiciones de satisfacción')),
                ('expire_at', models.DateField(verbose_name='Fecha límite de la fase')),
                ('begin_at', models.DateField(verbose_name='Fecha de inicio')),
                ('accomplish_at', models.DateField(verbose_name='Fecha de cumplimiento')),
                ('renegotiation_at', models.DateField(verbose_name='Fecha de regenociación')),
                ('report_at', models.DateField(verbose_name='Fecha de reporte de Avance')),
                ('financial', models.CharField(max_length=64, verbose_name='Financieros')),
                ('operational', models.CharField(max_length=64, verbose_name='Operacionales')),
                ('other1', models.CharField(max_length=64, verbose_name='Otros')),
                ('other2', models.CharField(max_length=64, verbose_name='Otros')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_action', to='users.User', verbose_name='Observador')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_action', to='users.User', verbose_name='Cliente')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_create_by', to='users.User', verbose_name='Creado por')),
                ('parent_action', models.ManyToManyField(blank=True, null=True, related_name='_action_parent_action_+', to='workflow.Action', verbose_name='Acción hija')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_action', to='users.User', verbose_name='Realizador')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='users.User', verbose_name='Proyecto relacionado')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AddField(
            model_name='project',
            name='create_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_create_by', to='users.User', verbose_name='Creado por'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='financial',
            field=models.CharField(default=1, max_length=64, verbose_name='Financieros'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='operational',
            field=models.CharField(default=1, max_length=64, verbose_name='Operacionales'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='other1',
            field=models.CharField(default=1, max_length=64, verbose_name='Otros'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='other2',
            field=models.CharField(default=1, max_length=64, verbose_name='Otros'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='accomplish_at',
            field=models.DateField(verbose_name='Fecha de cumplimiento'),
        ),
        migrations.AlterField(
            model_name='project',
            name='begin_at',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='project',
            name='evaluation_at',
            field=models.DateField(verbose_name='Fecha de evaluación'),
        ),
        migrations.AlterField(
            model_name='project',
            name='execution_at',
            field=models.DateField(verbose_name='Fecha de ejecución'),
        ),
        migrations.AlterField(
            model_name='project',
            name='negotiation_at',
            field=models.DateField(verbose_name='Fecha de negociación'),
        ),
        migrations.AlterField(
            model_name='project',
            name='phase',
            field=models.CharField(choices=[('preparacion', 'Preparación'), ('negociacion', 'Negociación'), ('ejecucion', 'Ejecución'), ('evaluacion', 'Evaluación')], default='preparacion', max_length=11, verbose_name='Fase de proyecto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='preparation_at',
            field=models.DateField(verbose_name='Fecha de preparación'),
        ),
        migrations.AlterField(
            model_name='project',
            name='renegotiation_at',
            field=models.DateField(verbose_name='Fecha de regenociación'),
        ),
        migrations.AlterField(
            model_name='project',
            name='report_at',
            field=models.DateField(verbose_name='Fecha de reporte de Avance'),
        ),
    ]
