# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_auto_20170310_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='workflow.Project', verbose_name='Proyecto relacionado'),
        ),
    ]
