# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_auto_20170604_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='advance_report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_reported', to='workflow.Action', verbose_name='Reporte de avance'),
        ),
    ]
