# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_auto_20170312_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='parent_action',
            field=models.ManyToManyField(blank=True, related_name='_action_parent_action_+', to='workflow.Action', verbose_name='Acción hija'),
        ),
    ]
