# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default=1, upload_to='images/', verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
