# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-05 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_auto_20170604_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectt', to='workflow.Action', verbose_name='Proyecto relacionado'),
        ),
    ]
