# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_auto_20170312_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='clasification',
            field=models.CharField(choices=[('estandar', 'Estándar'), ('piloto', 'Piloto'), ('jardin', 'Jardín')], default='estandar', max_length=8, verbose_name='Tipos de proyecto'),
        ),
    ]
