# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_auto_20170324_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Imagen'),
        ),
    ]
