# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-22 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_auto_20170605_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='advance_report',
        ),
        migrations.RemoveField(
            model_name='action',
            name='ejecution_report',
        ),
        migrations.AddField(
            model_name='report',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_report', to='workflow.Action', verbose_name='Acción'),
        ),
    ]
