# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_auto_20170324_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='is_renegotiated',
            field=models.BooleanField(default=False, verbose_name='Renegociado'),
        ),
        migrations.AddField(
            model_name='action',
            name='progress',
            field=models.CharField(choices=[('0', '0'), ('10', '10'), ('20', '20'), ('30', '30'), ('40', '40'), ('50', '50'), ('60', '60'), ('70', '70'), ('80', '80'), ('90', '90'), ('100', '100')], default='0', max_length=3, verbose_name='Porcentaje de avance'),
        ),
        migrations.AddField(
            model_name='action',
            name='promise',
            field=models.CharField(choices=[('Proceso', 'Proceso'), ('Cumplida', 'Cumplida'), ('Incumplida', 'Incumplida')], default='Proceso', max_length=10, verbose_name='Promesa'),
        ),
        migrations.AddField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada')], default='Abierta', max_length=7, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Nombre de la acción'),
        ),
    ]
