# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 02:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_auto_20170329_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='parent_action',
        ),
        migrations.AddField(
            model_name='action',
            name='parent_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Action', verbose_name='Acción Padre'),
        ),
    ]
