# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-09 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_auto_20170622_1935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': 'Acción', 'verbose_name_plural': 'Acciones'},
        ),
    ]
