# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-11 04:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_auto_20170709_0612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=128, verbose_name='Mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_alert', to='workflow.Action', verbose_name='Acción')),
            ],
        ),
    ]
