# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0010_auto_20170330_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[('open', 'Abierta'), ('close', 'Cerrada')], default='Abierta', max_length=5, verbose_name='Estado'),
        ),
    ]
