# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_auto_20170330_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='promise',
            field=models.CharField(choices=[('process', 'Proceso'), ('kept', 'Cumplida'), ('empty', 'Incumplida')], default='Proceso', max_length=7, verbose_name='Promesa'),
        ),
    ]
