# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-13 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_alert_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='kind',
            field=models.CharField(choices=[('Before', 'Before'), ('Deadline', 'Deadline'), ('After', 'After')], default='Deadline', max_length=8, verbose_name='Tipos de alerta'),
            preserve_default=False,
        ),
    ]
