# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-17 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0012_alert_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='accepted_at',
            field=models.DateField(blank=True, null=True, verbose_name='Aceptada en la fecha'),
        ),
        migrations.AddField(
            model_name='action',
            name='qualified_at',
            field=models.DateField(blank=True, null=True, verbose_name='Calificada en la fecha'),
        ),
        migrations.AlterField(
            model_name='action',
            name='advance_report_at',
            field=models.DateField(blank=True, null=True, verbose_name='Creado el reporte de avance en la fecha'),
        ),
        migrations.AlterField(
            model_name='action',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Creada en la fecha'),
        ),
        migrations.AlterField(
            model_name='action',
            name='ejecution_report_at',
            field=models.DateField(blank=True, null=True, verbose_name='Creado el reporte de ejecución en la fecha'),
        ),
        migrations.AlterField(
            model_name='action',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de la última actualización'),
        ),
    ]
