# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0012_auto_20170330_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='is_renegotiated',
        ),
        migrations.AlterField(
            model_name='action',
            name='progress',
            field=models.CharField(choices=[('0', '0'), ('25', '25'), ('50', '50'), ('75', '75'), ('100', '100')], default='0', max_length=3, verbose_name='Porcentaje de avance'),
        ),
        migrations.AlterField(
            model_name='action',
            name='promise',
            field=models.CharField(choices=[('created', 'Creada'), ('accepted', 'Aceptada'), ('reported', 'Reportada'), ('kept', 'Cumplida'), ('empty', 'Incumplida'), ('negotiating', 'Negociando'), ('unaccepted', 'No aceptada')], default='created', max_length=11, verbose_name='Promesa'),
        ),
        migrations.AlterField(
            model_name='action',
            name='renegotiation_at',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de regenociación'),
        ),
        migrations.AlterField(
            model_name='action',
            name='report_at',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de reporte de Avance'),
        ),
        migrations.AlterField(
            model_name='project',
            name='renegotiation_at',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de regenociación'),
        ),
        migrations.AlterField(
            model_name='project',
            name='report_at',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de reporte de Avance'),
        ),
    ]
