# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0013_auto_20170409_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='phase',
            field=models.CharField(choices=[('Preparación', 'Preparación'), ('Negociación', 'Negociación'), ('Ejecución', 'Ejecución'), ('Evaluación', 'Evaluación')], default='preparacion', max_length=11, verbose_name='Fase de la acción'),
        ),
        migrations.AlterField(
            model_name='action',
            name='promise',
            field=models.CharField(choices=[('Creada', 'Creada'), ('Aceptada', 'Aceptada'), ('Reportada', 'Reportada'), ('Cumplida', 'Cumplida'), ('Incumplida', 'Incumplida'), ('Negociando', 'Negociando'), ('No aceptada', 'No aceptada')], default='created', max_length=11, verbose_name='Promesa'),
        ),
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[('Abierta', 'Abierta'), ('Concluida satisfactoriamente', 'Concluida satisfactoriamente'), ('Concluida insatisfactoriamente', 'Concluida no satisfactoriamente')], default='Abierta', max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='project',
            name='clasification',
            field=models.CharField(choices=[('Estándar', 'Estándar'), ('Piloto', 'Piloto'), ('Jardín', 'Jardín')], default='estandar', max_length=8, verbose_name='Tipos de proyecto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='phase',
            field=models.CharField(choices=[('Preparación', 'Preparación'), ('Negociación', 'Negociación'), ('Ejecución', 'Ejecución'), ('Evaluación', 'Evaluación')], default='preparacion', max_length=11, verbose_name='Fase de proyecto'),
        ),
    ]
