# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-19 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0013_auto_20170717_0258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'verbose_name': 'Alerta', 'verbose_name_plural': 'Alertas'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Reporte', 'verbose_name_plural': 'Reportes'},
        ),
        migrations.AlterField(
            model_name='action',
            name='kind',
            field=models.CharField(choices=[('Estándar', 'Estándar'), ('Piloto', 'Piloto'), ('Jardín', 'Jardín')], default='estandar', max_length=8, verbose_name='Tipos'),
        ),
        migrations.AlterField(
            model_name='action',
            name='phase',
            field=models.CharField(choices=[('Preparación', 'Preparación'), ('Negociación', 'Negociación'), ('Ejecución', 'Ejecución'), ('Evaluación', 'Evaluación')], default='preparacion', max_length=11, verbose_name='Fase'),
        ),
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptada', 'Aceptada'), ('Ejecutada', 'Ejecutada'), ('Satisfactoria', 'Satisfactoria'), ('Insatisfactoria', 'Insatisfactoria')], default='Pendiente', max_length=16, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='message',
            field=models.TextField(max_length=128, verbose_name='Mensaje'),
        ),
    ]
