# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-25 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0014_auto_20170719_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=256, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fechade creacion')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_comment', to='workflow.Action', verbose_name='Acción')),
            ],
            options={
                'verbose_name_plural': 'Comentarios',
                'verbose_name': 'Comentario',
            },
        ),
    ]
