# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-05 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0015_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='satisfactions',
            field=models.TextField(max_length=1600, verbose_name='Condiciones de satisfacción'),
        ),
        migrations.AlterField(
            model_name='action',
            name='toDo',
            field=models.TextField(max_length=1600, verbose_name='¿Qué y como se realizará?'),
        ),
    ]
