# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0015_auto_20170415_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='expire_at',
        ),
        migrations.RemoveField(
            model_name='action',
            name='renegotiation_at',
        ),
        migrations.AlterField(
            model_name='action',
            name='report_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de reporte de Avance'),
            preserve_default=False,
        ),
    ]
