# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 22:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0016_auto_20170415_0611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='clasification',
            new_name='kind',
        ),
    ]
