# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-18 03:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0017_auto_20170818_0241'),
        ('workflow', '0017_message_sender'),
    ]

    operations = [
    ]
