# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0017_auto_20170415_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.CharField(choices=[('0', '0'), ('25', '25'), ('50', '50'), ('75', '75'), ('100', '100')], default='0', max_length=3, verbose_name='Porcentaje de avance')),
                ('accomplished', models.TextField(max_length=1024, verbose_name='Relizado')),
                ('pending', models.TextField(max_length=1024, verbose_name='Pendiente')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de creación')),
            ],
        ),
        migrations.AlterField(
            model_name='action',
            name='satisfactions',
            field=models.TextField(max_length=1024, verbose_name='Condiciones de satisfacción'),
        ),
        migrations.AlterField(
            model_name='action',
            name='toDo',
            field=models.TextField(max_length=1024, verbose_name='¿Qué y como se realizará?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='report_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de reporte de Avance'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='satisfactions',
            field=models.TextField(max_length=1024, verbose_name='Condiciones de satisfacción'),
        ),
        migrations.AlterField(
            model_name='project',
            name='toDo',
            field=models.TextField(max_length=1024, verbose_name='¿Qué y como se realizará?'),
        ),
        migrations.AddField(
            model_name='report',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_report', to='workflow.Action', verbose_name='Acción'),
        ),
        migrations.AddField(
            model_name='report',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_report', to='workflow.Project', verbose_name='Proyecto'),
        ),
    ]
