# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 06:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0018_auto_20170418_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='create_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='report_create_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
            preserve_default=False,
        ),
    ]
