# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-18 03:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0018_merge_20170818_0329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
    ]
