# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0019_report_create_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[('Abierta', 'Abierta'), ('Satisfactorias', 'Satisfactorias'), ('Insatisfactorias', 'Insatisfactorias')], default='Abierta', max_length=30, verbose_name='Estado'),
        ),
    ]
