# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0020_auto_20170420_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='progress',
        ),
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[('Abierta', 'Abierta'), ('Satisfactoria', 'Satisfactoria'), ('Insatisfactoria', 'Insatisfactoria')], default='Abierta', max_length=30, verbose_name='Estado'),
        ),
    ]
