# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0021_auto_20170421_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='promise',
            field=models.CharField(choices=[('Creada', 'Creada'), ('Aceptada', 'Aceptada'), ('Reportada', 'Reportada'), ('Cumplida', 'Cumplida'), ('Incumplida', 'Incumplida'), ('Negociando', 'Negociando'), ('No aceptada', 'No aceptada')], default='created', max_length=11, verbose_name='Promesa'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Abierta', 'Abierta'), ('Satisfactoria', 'Satisfactoria'), ('Insatisfactoria', 'Insatisfactoria')], default='Abierta', max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='action',
            name='promise',
            field=models.CharField(choices=[('Creada', 'Creada'), ('Aceptada', 'Aceptada'), ('Reportada', 'Reportada'), ('Cumplida', 'Cumplida'), ('Incumplida', 'Incumplida'), ('Calificada', 'Calificada'), ('Negociando', 'Negociando'), ('No aceptada', 'No aceptada')], default='created', max_length=11, verbose_name='Promesa'),
        ),
    ]
