# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0022_auto_20170502_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='promise',
        ),
        migrations.RemoveField(
            model_name='project',
            name='promise',
        ),
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[('Creada', 'Creada'), ('Aceptada', 'Aceptada'), ('Reportada', 'Reportada'), ('Terminada', 'Terminada'), ('Satisfactoria', 'Satisfactoria'), ('Insatisfactoria', 'Insatisfactoria'), ('Negociando', 'Negociando'), ('No aceptada', 'No aceptada')], default='Abierta', max_length=16, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Creada', 'Creada'), ('Aceptada', 'Aceptada'), ('Reportada', 'Reportada'), ('Terminada', 'Terminada'), ('Satisfactoria', 'Satisfactoria'), ('Insatisfactoria', 'Insatisfactoria'), ('Negociando', 'Negociando'), ('No aceptada', 'No aceptada')], default='Abierta', max_length=16, verbose_name='Estado'),
        ),
    ]
