# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0023_auto_20170508_0742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
