# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-13 04:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0024_auto_20170509_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='create_by',
        ),
        migrations.RemoveField(
            model_name='report',
            name='create_by',
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='project_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='report_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[('Creada', 'Creada'), ('Aceptada', 'Aceptada'), ('Reportada', 'Reportada'), ('Terminada', 'Terminada'), ('Satisfactoria', 'Satisfactoria'), ('Insatisfactoria', 'Insatisfactoria'), ('Negociando', 'Negociando'), ('No aceptada', 'No aceptada')], default='Creada', max_length=16, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Creada', 'Creada'), ('Aceptada', 'Aceptada'), ('Reportada', 'Reportada'), ('Terminada', 'Terminada'), ('Satisfactoria', 'Satisfactoria'), ('Insatisfactoria', 'Insatisfactoria'), ('Negociando', 'Negociando'), ('No aceptada', 'No aceptada')], default='Creada', max_length=16, verbose_name='Estado'),
        ),
    ]
