# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0025_auto_20170513_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='advance_report_at',
            field=models.DateField(null=True, verbose_name='Fecha de creación de reporte de Avance'),
        ),
        migrations.AddField(
            model_name='project',
            name='ejecution_report_at',
            field=models.DateField(null=True, verbose_name='Fecha de creación de reporte de Ejecución'),
        ),
    ]
