# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0026_auto_20170522_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[('Creada', 'Creada'), ('Aceptada', 'Aceptada'), ('Terminada', 'Terminada'), ('Satisfactoria', 'Satisfactoria'), ('Insatisfactoria', 'Insatisfactoria'), ('Negociando', 'Negociando'), ('No aceptada', 'No aceptada')], default='Creada', max_length=16, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='project',
            name='advance_report_at',
            field=models.DateTimeField(null=True, verbose_name='Fecha de creación de reporte de Avance'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ejecution_report_at',
            field=models.DateTimeField(null=True, verbose_name='Fecha de creación de reporte de Ejecución'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Creada', 'Creada'), ('Aceptada', 'Aceptada'), ('Terminada', 'Terminada'), ('Satisfactoria', 'Satisfactoria'), ('Insatisfactoria', 'Insatisfactoria'), ('Negociando', 'Negociando'), ('No aceptada', 'No aceptada')], default='Creada', max_length=16, verbose_name='Estado'),
        ),
    ]
