# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0027_auto_20170522_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='advance_report_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de creación de reporte de Avance'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ejecution_report_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de creación de reporte de Ejecución'),
        ),
    ]
