# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0028_auto_20170522_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='advance_report_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de creación de reporte de Avance'),
        ),
        migrations.AddField(
            model_name='action',
            name='ejecution_report_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de creación de reporte de Ejecución'),
        ),
    ]
