# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0029_auto_20170522_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='advance_report_at',
            field=models.DateTimeField(auto_now=True, default=1, verbose_name='Fecha de creación del reporte de avance'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='action',
            name='ejecution_report_at',
            field=models.DateTimeField(auto_now=True, default=1, verbose_name='Fecha de creación del reporte de ejecución'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='action',
            name='financial',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Financieros'),
        ),
        migrations.AlterField(
            model_name='action',
            name='operational',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Operacionales'),
        ),
        migrations.AlterField(
            model_name='action',
            name='other1',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Otros'),
        ),
        migrations.AlterField(
            model_name='action',
            name='other2',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Otros'),
        ),
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptada', 'Aceptada'), ('Ejecutada', 'Ejecutada'), ('Satisfactoria', 'Satisfactoria'), ('Insatisfactoria', 'Insatisfactoria'), ('Negociando', 'Negociando'), ('No aceptada', 'No aceptada')], default='Pendiente', max_length=16, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='project',
            name='advance_report_at',
            field=models.DateTimeField(null=True, verbose_name='Fecha de creación del reporte de avance'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ejecution_report_at',
            field=models.DateTimeField(null=True, verbose_name='Fecha de creación del reporte de ejecución'),
        ),
        migrations.AlterField(
            model_name='project',
            name='financial',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Financieros'),
        ),
        migrations.AlterField(
            model_name='project',
            name='operational',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Operacionales'),
        ),
        migrations.AlterField(
            model_name='project',
            name='other1',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Otros'),
        ),
        migrations.AlterField(
            model_name='project',
            name='other2',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Otros'),
        ),
        migrations.AlterField(
            model_name='project',
            name='report_at',
            field=models.DateField(verbose_name='Fecha de reporte de avance'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptada', 'Aceptada'), ('Ejecutada', 'Ejecutada'), ('Satisfactoria', 'Satisfactoria'), ('Insatisfactoria', 'Insatisfactoria'), ('Negociando', 'Negociando'), ('No aceptada', 'No aceptada')], default='Pendiente', max_length=16, verbose_name='Estado'),
        ),
    ]
