# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_baseuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='photo',
            field=models.ImageField(default=1, upload_to='photos/', verbose_name='Foto'),
            preserve_default=False,
        ),
    ]
