# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170324_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='cel_phone',
            field=models.CharField(default=111111111, max_length=16, verbose_name='Teléfono Móvil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseuser',
            name='position',
            field=models.CharField(choices=[('commercial officer', 'Directora Comercial'), ('national sales manager', 'Gerente Nacional de Ventas'), ('product line manager', 'Gerente de Línea de Productos'), ('corporate marketing Manager', 'Gerente de Marketing Corporativo'), ('regional sales manager', 'Gerente Regional de Ventas'), ('district manager', 'Gerente Distrital'), ('coordinator', 'Coordinador')], default='commercial officer', max_length=32, verbose_name='Posición'),
            preserve_default=False,
        ),
    ]
