# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170328_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='photo',
            field=models.ImageField(upload_to='photos/', verbose_name='Foto'),
        ),
    ]
