# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170329_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='position',
            field=models.CharField(choices=[('Directora Comercial', 'Directora Comercial'), ('Gerente Nacional de Ventas', 'Gerente Nacional de Ventas'), ('Gerente de Línea de Productos', 'Gerente de Línea de Productos'), ('Gerente de Marketing Corporativo', 'Gerente de Marketing Corporativo'), ('Gerente Regional de Ventas', 'Gerente Regional de Ventas'), ('Gerente Distrital', 'Gerente Distrital'), ('Coordinador', 'Coordinador')], max_length=32, verbose_name='Posición'),
        ),
    ]
