# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-13 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20170522_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='position',
            field=models.CharField(choices=[('Directora Comercial', 'Directora Comercial'), ('Gerente Nacional de Ventas', 'Gerente Nacional de Ventas'), ('Gerente de Línea de Productos', 'Gerente de Línea de Productos'), ('Gerente de Marketing Corporativo', 'Gerente de Marketing Corporativo'), ('Gerente Regional de Ventas', 'Gerente Regional de Ventas'), ('Gerente Distrital', 'Gerente Distrital'), ('Coordinador', 'Coordinador'), ('Administrador', 'Administrador'), ('Gerente de línea sobrepeso y obesidad', 'Gerente de línea sobrepeso y obesidad'), ('Gerente de instituciones', 'Gerente de instituciones'), ('Coordinadora de mercadotecnia digital', 'Coordinadora de mercadotecnia digital'), ('Gerente de inteligencia de mercados', 'Gerente de inteligencia de mercados'), ('Gerente de mercadotecnia', 'Gerente de mercadotecnia'), ('Gerente de línea salud femenina', 'Gerente de línea salud femenina'), ('Gerente de línea Gastro', 'Gerente de línea Gastro'), ('Coordinadora de comunicación comercial/ventas', 'Coordinadora de comunicación comercial/ventas'), ('Gerente de la linea gastro', 'Gerente de la linea gastro'), ('Coordinador de marca línea gastro', 'Coordinador de marca línea gastro'), ('Especialista de capacitación fuerza de ventas', 'Coordinador de marca línea gastro'), ('Gerente asociado línea obesidad', 'Gerente asociado línea obesidad'), ('Gerente de productividad comercial', 'Gerente de productividad comercial'), ('Coordinador de marca línea salud femenina', 'Coordinador de marca línea salud femenina'), ('Cuenta clave', 'Cuenta clave')], max_length=132, verbose_name='Posición'),
        ),
    ]
