# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-19 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20170613_1731'),
        ('users', '0009_auto_20170613_1735'),
    ]

    operations = [
    ]
