# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-09 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_merge_20170619_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='position',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Coordinador', 'Coordinador'), ('Coordinadora de comunicación comercial/ventas', 'Coordinadora de comunicación comercial/ventas'), ('Coordinador de marca línea gastro', 'Coordinador de marca línea gastro'), ('Coordinadora de mercadotecnia digital', 'Coordinadora de mercadotecnia digital'), ('Coordinador de marca línea salud femenina', 'Coordinador de marca línea salud femenina'), ('Cuenta clave', 'Cuenta clave'), ('Directora comercial', 'Directora comercial'), ('Especialista de capacitación fuerza de ventas', 'Especialista de capacitación fuerza de ventas'), ('Gerente de instituciones', 'Gerente de instituciones'), ('Gerente de inteligencia de mercados', 'Gerente de inteligencia de mercados'), ('Gerente de línea de productos', 'Gerente de línea de productos'), ('Gerente de línea gastro', 'Gerente de línea Gastro'), ('Gerente de línea salud femenina', 'Gerente de línea salud femenina'), ('Gerente de línea sobrepeso y obesidad', 'Gerente de línea sobrepeso y obesidad'), ('Gerente de marketing corporativo', 'Gerente de marketing corporativo'), ('Gerente de mercadotecnia', 'Gerente de mercadotecnia'), ('Gerente de productividad comercial', 'Gerente de productividad comercial'), ('Gerente asociado línea obesidad', 'Gerente asociado línea obesidad'), ('Gerente distrital', 'Gerente distrital'), ('Gerente regional de ventas', 'Gerente regional de ventas'), ('Gerente nacional de ventas', 'Gerente nacional de ventas'), ('Gerente cuentas clave', 'Gerente Cuentas Clave'), ('Sub director comercial', 'Sub director Comercial')], max_length=132, verbose_name='Posición'),
        ),
    ]
