# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20170309_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('preparacion', 'Preparaci\xf3n'), ('negociacion', 'Negociaci\xf3n'), ('ejecucion', 'Ejecuci\xf3n'), ('evaluacion', 'Evaluaci\xf3n')], default='created', max_length=11, verbose_name='Estado')),
                ('name', models.CharField(max_length=64, verbose_name='Nombre')),
                ('toDo', models.TextField(max_length=512, verbose_name='\xbfQu\xe9 y como se realizar\xe1?')),
                ('satisfactions', models.TextField(max_length=512, verbose_name='Condiciones de satisfacci\xf3n')),
                ('preparation_at', models.DateTimeField(verbose_name='Fecha de preparaci\xf3n')),
                ('negotiation_at', models.DateTimeField(verbose_name='Fecha de negociaci\xf3n')),
                ('execution_at', models.DateTimeField(verbose_name='Fecha de ejecuci\xf3n')),
                ('evaluation_at', models.DateTimeField(verbose_name='Fecha de evaluaci\xf3n')),
                ('begin_at', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('accomplish_at', models.DateTimeField(verbose_name='Fecha de cumplimiento')),
                ('renegotiation_at', models.DateTimeField(verbose_name='Fecha de regenociaci\xf3n')),
                ('report_at', models.DateTimeField(verbose_name='Fecha de reporte de Avance')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de creaci\xf3n')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizaci\xf3n')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_project', to='users.User', verbose_name='Observador')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_project', to='users.User', verbose_name='Cliente')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_project', to='users.User', verbose_name='Realizador')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyecto',
            },
        ),
    ]
